version: "3.9"

services:
  db:
    image: postgres:17-alpine
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/home

volumes:
    postgres_data: